export const envKeys = {
  OLLAMA_MODEL_NAME: 'OLLAMA_MODEL_NAME',
  TAVILY_API_KEY: 'TAVILY_API_KEY',
  ENVIRONMENT: 'ENVIRONMENT',
  SCRAPIN_API_KEY: 'SCRAPIN_API_KEY',
  NAME_VALIDATOR_MODEL_NAME: 'NAME_VALIDATOR_MODEL_NAME',
};
